name: find_invest_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  go_router: ^15.1.2
  im_stepper: ^1.0.1+1

  hive_flutter: ^1.1.0
  introduction_screen: ^3.1.17
  logger: ^2.6.0
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_animate: ^4.5.2
  equatable: ^2.0.7

  # JSON serialization
  json_annotation: ^4.8.1

  # Freezed for immutable data classes
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  dartz: ^0.10.1
  connectivity_plus: ^6.1.4
  dropdown_button2: ^2.3.9
  lottie: ^3.2.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

   # Freezed code generator
  freezed: ^2.4.5

  # JSON code generator
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
